version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - automated
    reviewers:
      - your-github-username
